### ISSUE TITLE
lastname_firstname as username 

### ISSUE THREAD

**Issue by mb-wali** [tu-graz-library/invenio-shibboleth#4]
username is a unique field therefor email address is also a unique attribute.
set the username to attribute email.
@utnapischtim

**Comment by mb-wali** [comment]
according to validation for username field: ```Username must start with a letter, be at least three characters long and only contain alphanumeric characters, dashes and underscores.```. we cannot use email address.
solution: combine both lastname with underscore and then firstname: ```adam_sean```.

**Comment by utnapischtim** [comment]
would it be possible to only use the part before of the @ sign of the email?

the point is, it could be possible that we have persons with the same name on the university, and it is not that rare as you might think

**Comment by mb-wali** [comment]
> would it be possible to only use the part before of the @ sign of the email?
> 
> the point is, it could be possible that we have persons with the same name on the university, and it is not that rare as you might think
No, I tried ```username must start with a letter``` and this id starts with a number.

**Comment by mb-wali** [comment]
## Username
```prefix + eduPersonPrincipalName``` = ```TUG77ABA62CDB768BF1```
